{{
    config(
        materialized='table',
        transient=false,
        schema='SILVER',
        query_tag='dbt_run_transactions'
    )
}}

WITH raw AS (
    SELECT 
        SOURCE_FILE, 
        EXTRACTED_AT, 
        TRANSACTION_ID, 
        CUSTOMER_ID, 
        SRC_ACCOUNT, 
        DEST_ACCOUNT, 
        AMOUNT, 
        CURRENCY, 
        STATUS, 
        CREATED_AT, 
        PROCESSED_AT, 
        CHANNEL, 
        MERCHANT_CATEGORY, 
        RAW_PAYLOAD
    FROM {{ source('medallion', 'transactions_raw') }}
),

deduped AS (
    SELECT
        SOURCE_FILE              AS SOURCE_FILE,
        EXTRACTED_AT             AS EXTRACTED_AT,
        TRANSACTION_ID           AS TRANSACTION_ID,
        CUSTOMER_ID              AS CUSTOMER_ID,
        SRC_ACCOUNT              AS SRC_ACCOUNT,
        DEST_ACCOUNT             AS DEST_ACCOUNT,
        AMOUNT                   AS AMOUNT,
        CURRENCY                 AS CURRENCY,
        STATUS                   AS STATUS,
        CREATED_AT               AS CREATED_AT,
        PROCESSED_AT             AS PROCESSED_AT,
        CHANNEL                  AS CHANNEL,
        MERCHANT_CATEGORY        AS MERCHANT_CATEGORY,
        RAW_PAYLOAD              AS RAW_PAYLOAD
    FROM raw
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TRANSACTION_ID 
        ORDER BY EXTRACTED_AT DESC
    ) = 1
)

SELECT
    TRIM(SOURCE_FILE) AS SOURCE_FILE,
    TRY_TO_TIMESTAMP_NTZ(EXTRACTED_AT) AS EXTRACTED_AT,
    TRIM(TRANSACTION_ID) AS TRANSACTION_ID, 
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID, 
    TRIM(SRC_ACCOUNT) AS SRC_ACCOUNT, 
    TRIM(DEST_ACCOUNT) AS DEST_ACCOUNT, 
    TRY_TO_DECIMAL(AMOUNT,18,2) AS AMOUNT,
    TRIM(COALESCE(UPPER(CURRENCY),'UNKNOWN')) AS CURRENCY,
    TRIM(COALESCE(UPPER(STATUS),'UNKNOWN')) AS STATUS,
    TRY_TO_TIMESTAMP_NTZ(CREATED_AT) AS CREATED_AT,
    TRY_TO_TIMESTAMP_NTZ(PROCESSED_AT) AS PROCESSED_AT,
    TRIM(UPPER(CHANNEL)) AS CHANNEL, 
    TRIM(MERCHANT_CATEGORY) AS MERCHANT_CATEGORY, 
    RAW_PAYLOAD
FROM deduped
WHERE 
    --Null Handling for Mandatory Fields
    TRANSACTION_ID IS NOT NULL
    AND CUSTOMER_ID IS NOT NULL
    --Invalid Value Filtering
    AND TRIM(UPPER(CURRENCY)) IN ('USD', 'INR', 'EUR')
    AND TRY_TO_DECIMAL(AMOUNT,18,2) > 0
    AND (PROCESSED_AT IS NULL OR TRY_TO_TIMESTAMP_NTZ(PROCESSED_AT)<CURRENT_TIMESTAMP())
    AND TRY_TO_TIMESTAMP_NTZ(CREATED_AT)<CURRENT_TIMESTAMP()
    AND TRIM(UPPER(STATUS)) IN ('COMPLETED', 'PENDING', 'FAILED')
    --Business Rules
    AND NOT(TRIM(UPPER(STATUS))='COMPLETED' AND PROCESSED_AT IS NULL)
    AND NOT(TRIM(UPPER(STATUS))='PENDING' AND PROCESSED_AT IS NOT NULL)
    AND TRY_TO_DECIMAL(AMOUNT,18,2) BETWEEN 1 AND 1000000
    AND (
            PROCESSED_AT IS NULL 
            OR TRY_TO_TIMESTAMP_NTZ(CREATED_AT) <= TRY_TO_TIMESTAMP_NTZ(PROCESSED_AT)
        )
    AND TRY_TO_TIMESTAMP_NTZ(EXTRACTED_AT) >= TRY_TO_TIMESTAMP_NTZ(CREATED_AT)
    